#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Genera el PDF "Tabla Comparativa de Cumplimiento Legal — Reportes de Asistencia".
Documento de referencia que cruza:
  - Los 10 endpoints de /api/reports/
  - Los campos que cada uno expone
  - El articulado legal mexicano que cada campo cumple (LFT, NOM-035, NOM-037, LSS)

Salida: /home/z/my-project/public/tabla-comparativa-cumplimiento-legal.pdf
"""

import os
import sys
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether, Image
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f6f6f5')
SECTION_BG    = colors.HexColor('#f1f1f0')
CARD_BG       = colors.HexColor('#ecebe9')
TABLE_STRIPE  = colors.HexColor('#f0efed')
HEADER_FILL   = colors.HexColor('#6a5e3b')
COVER_BLOCK   = colors.HexColor('#7d7661')
BORDER        = colors.HexColor('#cdc9be')
ICON          = colors.HexColor('#a8914b')
ACCENT        = colors.HexColor('#96781b')
ACCENT_2      = colors.HexColor('#7052cb')
TEXT_PRIMARY  = colors.HexColor('#262522')
TEXT_MUTED    = colors.HexColor('#77756e')
SEM_SUCCESS   = colors.HexColor('#44905d')
SEM_WARNING   = colors.HexColor('#96783c')
SEM_ERROR     = colors.HexColor('#9b4740')
SEM_INFO      = colors.HexColor('#527aa1')

# ━━ Fuentes (Helvetica nativa de ReportLab — suficiente para ES) ━━
BASE_FONT = 'Helvetica'
BASE_FONT_BOLD = 'Helvetica-Bold'
BASE_FONT_OBL = 'Helvetica-Oblique'

# ━━ Salida ━━
OUT_DIR = '/home/z/my-project/public'
OUT_PATH = os.path.join(OUT_DIR, 'tabla-comparativa-cumplimiento-legal.pdf')
os.makedirs(OUT_DIR, exist_ok=True)

# ━━ Página ━━ (landscape A4 para acomodar la matriz ancha)
PAGE_SIZE = landscape(A4)  # 842 × 595 pt
LEFT_MARGIN = 14 * mm
RIGHT_MARGIN = 14 * mm
TOP_MARGIN = 16 * mm
BOTTOM_MARGIN = 16 * mm
CONTENT_W = PAGE_SIZE[0] - LEFT_MARGIN - RIGHT_MARGIN  # ≈ 814 pt

# ━━ Estilos ━━
styles = getSampleStyleSheet()

st_title = ParagraphStyle(
    'TitleCustom', parent=styles['Title'],
    fontName=BASE_FONT_BOLD, fontSize=20, leading=24,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceAfter=4,
)
st_subtitle = ParagraphStyle(
    'SubtitleCustom', parent=styles['Normal'],
    fontName=BASE_FONT, fontSize=10.5, leading=14,
    textColor=TEXT_MUTED, alignment=TA_LEFT, spaceAfter=10,
)
st_h2 = ParagraphStyle(
    'H2Custom', parent=styles['Heading2'],
    fontName=BASE_FONT_BOLD, fontSize=13, leading=16,
    textColor=HEADER_FILL, alignment=TA_LEFT,
    spaceBefore=14, spaceAfter=6,
)
st_h3 = ParagraphStyle(
    'H3Custom', parent=styles['Heading3'],
    fontName=BASE_FONT_BOLD, fontSize=11, leading=14,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
    spaceBefore=8, spaceAfter=4,
)
st_body = ParagraphStyle(
    'BodyCustom', parent=styles['Normal'],
    fontName=BASE_FONT, fontSize=9.5, leading=13,
    textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, spaceAfter=4,
)
st_body_small = ParagraphStyle(
    'BodySmall', parent=styles['Normal'],
    fontName=BASE_FONT, fontSize=8.5, leading=11,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceAfter=2,
)
st_cell = ParagraphStyle(
    'Cell', parent=styles['Normal'],
    fontName=BASE_FONT, fontSize=7.5, leading=9.5,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
)
st_cell_center = ParagraphStyle(
    'CellCenter', parent=st_cell, alignment=TA_CENTER,
)
st_cell_bold = ParagraphStyle(
    'CellBold', parent=st_cell, fontName=BASE_FONT_BOLD,
)
st_cell_header = ParagraphStyle(
    'CellHeader', parent=styles['Normal'],
    fontName=BASE_FONT_BOLD, fontSize=7.5, leading=9.5,
    textColor=colors.white, alignment=TA_CENTER,
)
st_legend = ParagraphStyle(
    'Legend', parent=styles['Normal'],
    fontName=BASE_FONT, fontSize=8.5, leading=11,
    textColor=TEXT_MUTED, alignment=TA_LEFT, spaceAfter=2,
)
st_footer = ParagraphStyle(
    'Footer', parent=styles['Normal'],
    fontName=BASE_FONT_OBL, fontSize=7.5, leading=9,
    textColor=TEXT_MUTED, alignment=TA_CENTER,
)

# ━━ Helpers ━━
def P(text, style=st_cell):
    """Atajo para Paragraph."""
    return Paragraph(text, style)

def chk(state):
    """Devuelve un Paragraph con el símbolo de estado."""
    if state == 'ok':
        return Paragraph(f'<font color="#44905d"><b>✓</b></font>', st_cell_center)
    if state == 'warn':
        return Paragraph(f'<font color="#96783c"><b>⚠</b></font>', st_cell_center)
    if state == 'no':
        return Paragraph(f'<font color="#9b4740"><b>✗</b></font>', st_cell_center)
    return Paragraph('—', st_cell_center)

def cell_state(state, label=''):
    """Celda con icono + etiqueta corta."""
    icon = {'ok': '✓', 'warn': '⚠', 'no': '✗', '': '—'}.get(state, '—')
    color = {'ok': '#44905d', 'warn': '#96783c', 'no': '#9b4740', '': '#77756e'}.get(state, '#77756e')
    txt = f'<font color="{color}"><b>{icon}</b></font>'
    if label:
        txt += f' <font size="6.5" color="#77756e">{label}</font>'
    return Paragraph(txt, st_cell_center)

# ━━ Header / Footer en cada página ━━
def on_page(canvas, doc):
    canvas.saveState()
    # Línea superior fina
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(LEFT_MARGIN, PAGE_SIZE[1] - TOP_MARGIN + 6,
                PAGE_SIZE[0] - RIGHT_MARGIN, PAGE_SIZE[1] - TOP_MARGIN + 6)
    # Header text
    canvas.setFont(BASE_FONT, 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LEFT_MARGIN, PAGE_SIZE[1] - TOP_MARGIN + 10,
                      'Control de Asistencia — Cumplimiento Legal (LFT · NOM-035 · NOM-037 · LSS)')
    canvas.drawRightString(PAGE_SIZE[0] - RIGHT_MARGIN, PAGE_SIZE[1] - TOP_MARGIN + 10,
                           f'Pág. {doc.page}')
    # Footer
    canvas.line(LEFT_MARGIN, BOTTOM_MARGIN - 6,
                PAGE_SIZE[0] - RIGHT_MARGIN, BOTTOM_MARGIN - 6)
    canvas.setFont(BASE_FONT_OBL, 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawCentredString(PAGE_SIZE[0] / 2, BOTTOM_MARGIN - 14,
                             'Documento de referencia interna — Generado a partir del inventario de endpoints /api/reports/')
    canvas.restoreState()

# ━━ Construcción del documento ━━
doc = SimpleDocTemplate(
    OUT_PATH,
    pagesize=PAGE_SIZE,
    leftMargin=LEFT_MARGIN, rightMargin=RIGHT_MARGIN,
    topMargin=TOP_MARGIN, bottomMargin=BOTTOM_MARGIN,
    title='Tabla Comparativa de Cumplimiento Legal — Reportes de Asistencia',
    author='Sistema de Control de Asistencia',
    subject='Matriz de cobertura LFT/NOM-035/NOM-037/LSS por reporte',
    creator='Z.ai',
)

story = []

# ─────────────────────────────────────────────────────────────────
# Título e introducción
# ─────────────────────────────────────────────────────────────────
story.append(P('Tabla Comparativa de Cumplimiento Legal', st_title))
story.append(P(
    'Reportes de Asistencia · Matriz de cobertura por articulado mexicano (LFT, NOM-035-STPS-2018, NOM-037-STPS-2023, LSS)',
    st_subtitle
))

intro_text = (
    'Este documento cruza los <b>10 endpoints</b> del módulo <font face="Helvetica-Oblique">/api/reports/</font> '
    'con los <b>conceptos legales</b> que cada uno computa para cumplir la legislación mexicana aplicable '
    'al control de asistencia: Ley Federal del Trabajo (LFT), NOM-035-STPS-2018 (riesgo psicosocial), '
    'NOM-037-STPS-2023 (teletrabajo) y Ley del Seguro Social (LSS). '
    'Para cada concepto se marca si el reporte lo computa (<font color="#44905d"><b>✓</b></font>), '
    'lo hace parcialmente (<font color="#96783c"><b>⚠</b></font>) o no lo cubre (<font color="#9b4740"><b>✗</b></font>). '
    'Las celdas con ✓ muestran el nombre del campo devuelto por el endpoint.'
)
story.append(P(intro_text, st_body))
story.append(Spacer(1, 6))

# Leyenda
legend_data = [[
    P('<font color="#44905d"><b>✓</b></font> &nbsp; Computa el campo (cumple)', st_legend),
    P('<font color="#96783c"><b>⚠</b></font> &nbsp; Parcial / implícito / solo tooltip', st_legend),
    P('<font color="#9b4740"><b>✗</b></font> &nbsp; No cubre (gap legal)', st_legend),
]]
legend_tbl = Table(legend_data, colWidths=[CONTENT_W / 3] * 3)
legend_tbl.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, -1), SECTION_BG),
    ('BOX', (0, 0), (-1, -1), 0.5, BORDER),
    ('INNERGRID', (0, 0), (-1, -1), 0.25, BORDER),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 5),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
]))
story.append(legend_tbl)
story.append(Spacer(1, 10))

# ─────────────────────────────────────────────────────────────────
# TABLA 1 — Matriz de cobertura concepto × reporte
# ─────────────────────────────────────────────────────────────────
story.append(P('1. Matriz de cobertura por concepto legal', st_h2))
story.append(P(
    'Cada fila es un concepto legal; cada columna un reporte. La celda indica el campo '
    'devuelto por el endpoint (✓), una cobertura parcial (⚠) o la ausencia del concepto (✗).',
    st_body_small
))
story.append(Spacer(1, 4))

# Encabezados de columna — 11 cols: Concepto + 10 endpoints
COL_W = [
    150,  # Concepto
    52,   # incidences
    48,   # absences
    52,   # overtime
    48,   # emp-ot
    52,   # corrections
    48,   # daily
    56,   # comparative
    56,   # stps-format
    60,   # export
    56,   # my-export
]
# Ajustar a CONTENT_W
scale = CONTENT_W / sum(COL_W)
COL_W = [w * scale for w in COL_W]

# Títulos de columna en español (terminología del sistema)
ENDPOINTS = ['Incidencias', 'Ausencias', 'Horas extra', 'HE empleado', 'Correcciones', 'Diario', 'Comparativa', 'Formato STPS', 'Exportación', 'Mi exportación']

# Encabezado
header_row = [P('Concepto legal', st_cell_header)] + [P(e, st_cell_header) for e in ENDPOINTS]

# Datos: (concepto, [estados por endpoint], articulo)
# estados: ('ok', 'campo') | ('warn', 'nota') | ('no', '') | ('', '')
rows_data = [
    # ── Jornada y horas extra ──
    ('Días trabajados',
     [('ok', 'diasLaborados'), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('warn', 'records'), ('ok', 'presentDays'), ('ok', 'diasTrabajados'),
      ('ok', 'incidencias'), ('no', '')],
     'LFT art. 132 XXXIV'),
    ('Faltas injustificadas',
     [('ok', 'faltas'), ('ok', 'absentDays'), ('no', ''), ('no', ''), ('no', ''),
      ('ok', 'absent'), ('ok', 'absentDays'), ('ok', 'diasFalta'),
      ('ok', 'ausencias/incidencias'), ('no', '')],
     'LFT art. 42, 47'),
    ('Incapacidades (días)',
     [('ok', 'diasIncapacidad'), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('no', ''), ('no', ''), ('ok', 'diasIncapacidad'),
      ('ok', 'incidencias'), ('no', '')],
     'LSS art. 96, 170'),
    ('Vacaciones (días)',
     [('ok', 'diasVacaciones'), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('no', ''), ('no', ''), ('ok', 'diasVacac.'),
      ('ok', 'incidencias'), ('no', '')],
     'LFT art. 76–80'),
    ('Descansos trabajados',
     [('ok', 'diasDescanso'), ('no', ''), ('ok', 'restDayWorked'), ('ok', ''), ('no', ''),
      ('ok', 'restDayWorked'), ('ok', ''), ('ok', 'diasDescanso'),
      ('ok', 'incidencias/he'), ('ok', '')],
     'LFT art. 73'),
    ('Permisos (días)',
     [('warn', 'salteado'), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('no', ''), ('no', ''), ('ok', 'diasPermiso'),
      ('no', ''), ('no', '')],
     'LFT art. 132 XVII'),
    ('Retardos (conteo)',
     [('ok', 'retardos'), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('ok', 'late'), ('ok', 'lateDays'), ('ok', 'diasLlegoTarde'),
      ('ok', 'incidencias'), ('no', '')],
     'LFT art. 132 XXXIV'),
    ('Retardos (minutos)',
     [('no', ''), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('no', ''), ('no', ''), ('ok', 'totalRetardoMin'),
      ('no', ''), ('no', '')],
     'LFT art. 132 XXXIV'),
    ('Salidas anticipadas',
     [('ok', 'salidasAnt.'), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('ok', 'earlyLeave'), ('ok', 'earlyLeaveDays'), ('ok', 'diasSalioTarde'),
      ('ok', 'incidencias'), ('no', '')],
     'LFT art. 784'),
    ('Horas extra simples',
     [('ok', 'horasExtraMin'), ('no', ''), ('ok', 'overtimeMin'), ('ok', ''), ('no', ''),
      ('ok', 'totalOvertime'), ('ok', ''), ('no', ''),
      ('ok', 'he/diario'), ('ok', '')],
     'LFT art. 66'),
    ('Horas extra dobles',
     [('ok', 'horasExtraDoble'), ('no', ''), ('ok', ''), ('ok', ''), ('no', ''),
      ('ok', ''), ('ok', ''), ('ok', 'totalDobles'),
      ('ok', 'todos'), ('ok', '')],
     'LFT art. 66 (≤9h/sem)'),
    ('Horas extra triples',
     [('ok', 'horasExtraTriple'), ('no', ''), ('ok', ''), ('ok', ''), ('no', ''),
      ('ok', ''), ('ok', ''), ('ok', 'totalTriples'),
      ('ok', 'todos'), ('ok', '')],
     'LFT art. 68 (>9h/sem)'),

    # ── Descansos y primas ──
    ('Prima 100% descanso',
     [('ok', 'primaDescanso'), ('no', ''), ('ok', 'restDayPremium'), ('ok', ''), ('no', ''),
      ('ok', 'restDayPremium'), ('ok', ''), ('warn', 'implícito'),
      ('ok', ''), ('ok', '')],
     'LFT art. 73'),
    ('Prima dominical',
     [('ok', 'domingosTrab.'), ('no', ''), ('warn', 'isSunday'), ('warn', ''), ('no', ''),
      ('warn', 'isSunday'), ('no', ''), ('no', ''),
      ('no', ''), ('warn', 'Domingo S/N')],
     'LFT art. 71 (≥25%)'),
    ('Séptimo día',
     [('ok', 'diasSeptimo'), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('no', ''), ('no', ''), ('no', ''),
      ('no', ''), ('no', '')],
     'LFT art. 72'),
    ('Días festivos trabajados',
     [('ok', 'diasFestivos'), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('no', ''), ('no', ''), ('no', ''),
      ('no', ''), ('no', '')],
     'LFT art. 74–75'),

    # ── Jornada nocturna ──
    ('Minutos nocturnos',
     [('ok', 'minutosNocturnos'), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('ok', ''), ('ok', ''), ('ok', 'totalNocturno'),
      ('ok', 'diario/he'), ('no', '')],
     'LFT art. 60–61'),
    ('Jornada (D/N/M)',
     [('ok', 'jornadaNocturna'), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('ok', ''), ('ok', ''), ('ok', 'jornada'),
      ('ok', 'diario/he'), ('no', '')],
     'LFT art. 60'),

    # ── Trazabilidad y prueba ──
    ('Correcciones (trazabilidad)',
     [('no', ''), ('no', ''), ('no', ''), ('no', ''), ('ok', 'ruta'),
      ('warn', 'en registros'), ('no', ''), ('no', ''),
      ('ok', 'auditoría diario'), ('ok', '')],
     'LFT art. 132 XXXIV'),
    ('Geolocalización / IP',
     [('no', ''), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('ok', 'lat/long/IP'), ('no', ''), ('ok', 'fueraGeofence'),
      ('ok', 'auditoría diario'), ('no', '')],
     'NOM-037 art. 27'),
    ('Firma del empleado',
     [('no', ''), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('no', ''), ('no', ''), ('no', ''),
      ('no', ''), ('ok', 'Firmado')],
     'NOM-037 art. 27'),

    # ── IMSS / Seguridad social ──
    ('NSS (empleado)',
     [('no', ''), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('no', ''), ('no', ''), ('no', ''),
      ('ok', 'IMSS nss'), ('no', '')],
     'LSS art. 15, LFT art. 804 II'),
    ('Folio IMSS (incapacidad)',
     [('no', ''), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('no', ''), ('no', ''), ('no', ''),
      ('ok', 'IMSS folioIMSS'), ('no', '')],
     'LSS art. 15'),
    ('Riesgo de trabajo (tipo)',
     [('no', ''), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('no', ''), ('no', ''), ('no', ''),
      ('ok', 'IMSS RIESGO'), ('no', '')],
     'LSS art. 41, 51'),

    # ── Nómina (no implementado) ──
    ('Sueldo / nómina',
     [('no', ''), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('no', ''), ('no', ''), ('warn', 'salarioBase texto'),
      ('no', ''), ('no', '')],
     'LFT art. 804 II'),
    ('Deducciones (IMSS/ISR)',
     [('no', ''), ('no', ''), ('no', ''), ('no', ''), ('no', ''),
      ('no', ''), ('no', ''), ('no', ''),
      ('no', ''), ('no', '')],
     'LSS art. 36, 110'),
]

# Construir filas de la tabla
table_rows = [header_row]
for concepto, estados, articulo in rows_data:
    row = [P(f'<b>{concepto}</b><br/><font size="6.5" color="#77756e">{articulo}</font>', st_cell)]
    for estado, label in estados:
        row.append(cell_state(estado, label))
    table_rows.append(row)

matriz_tbl = Table(table_rows, colWidths=COL_W, repeatRows=1)
matriz_style = TableStyle([
    # Header
    ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('FONTNAME', (0, 0), (-1, 0), BASE_FONT_BOLD),
    ('FONTSIZE', (0, 0), (-1, 0), 7.5),
    ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
    ('VALIGN', (0, 0), (-1, 0), 'MIDDLE'),
    ('TOPPADDING', (0, 0), (-1, 0), 6),
    ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
    # Body
    ('VALIGN', (0, 1), (-1, -1), 'MIDDLE'),
    ('ALIGN', (1, 1), (-1, -1), 'CENTER'),
    ('ALIGN', (0, 1), (0, -1), 'LEFT'),
    ('LEFTPADDING', (0, 0), (-1, -1), 4),
    ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ('TOPPADDING', (0, 1), (-1, -1), 4),
    ('BOTTOMPADDING', (0, 1), (-1, -1), 4),
    ('FONTNAME', (0, 1), (-1, -1), BASE_FONT),
    ('FONTSIZE', (0, 1), (-1, -1), 7.5),
    # Grid
    ('GRID', (0, 0), (-1, -1), 0.4, BORDER),
    ('LINEBELOW', (0, 0), (-1, 0), 1.0, HEADER_FILL),
])
# Striping
for i in range(1, len(table_rows)):
    if i % 2 == 0:
        matriz_style.add('BACKGROUND', (0, i), (-1, i), TABLE_STRIPE)
    else:
        matriz_style.add('BACKGROUND', (0, i), (-1, i), colors.white)

matriz_tbl.setStyle(matriz_style)
story.append(matriz_tbl)
story.append(Spacer(1, 8))

# Nota al pie de la matriz
story.append(P(
    '<b>Nota:</b> Las celdas con nombre de campo (p. ej. <font face="Helvetica-Oblique">diasLaborados</font>) '
    'indican el nombre exacto del atributo devuelto por el endpoint en su respuesta JSON. '
    'El reporte de <b>exportación</b> es multi-reporte que genera CSV/XLSX según el parámetro <font face="Helvetica-Oblique">?type=</font>; '
    'la columna indica qué <font face="Helvetica-Oblique">tipo</font> incluye el concepto.',
    st_legend
))

story.append(PageBreak())

# ─────────────────────────────────────────────────────────────────
# TABLA 2 — Detalle de campos por reporte
# ─────────────────────────────────────────────────────────────────
story.append(P('2. Campos por reporte y su fundamento legal', st_h2))
story.append(P(
    'Para cada reporte, los campos principales que expone y el artículo de la legislación mexicana '
    'que cada campo ayuda a cumplir.',
    st_body_small
))
story.append(Spacer(1, 4))

# Tabla: Reporte | Campos principales | Cumplimiento legal
COL_W2 = [110, 330, 374]  # ≈ 814
scale2 = CONTENT_W / sum(COL_W2)
COL_W2 = [w * scale2 for w in COL_W2]

campos_header = [
    P('Reporte (ruta API)', st_cell_header),
    P('Campos principales que expone', st_cell_header),
    P('Cumplimiento legal (LFT / NOM / LSS)', st_cell_header),
]

campos_rows = [
    campos_header,
    [
        P('<b>Incidencias</b><br/><font size="6.5" color="#77756e">/api/reports/incidences</font>', st_cell),
        P('diasLaborados, faltas, retardos, salidasAnticipadas, horasExtraMinutos/Horas, '
          'horasExtraDobleMinutos, horasExtraTripleMinutos, horasTrabajadasMinutos/Horas, '
          'diasVacaciones, diasIncapacidad, diasDescansoTrabajado, primaDescansoMinutos/Horas, '
          '<b>domingosTrabajados</b>, <b>diasSeptimo</b>, <b>diasFestivosTrabajados</b>, '
          'minutosNocturnos, jornadaNocturna', st_cell),
        P('Art. 132 XXXIV (registro electrónico); art. 42, 47 (faltas); art. 66, 68 (HE dobles/triples); '
          'art. 71 (prima dominical); art. 72 (séptimo día); art. 73 (prima descanso); art. 75 (festivos); '
          'art. 76–80 (vacaciones); art. 60–61 (jornada nocturna); LSS art. 96, 170 (incapacidades)', st_cell),
    ],
    [
        P('<b>Ausencias</b><br/><font size="6.5" color="#77756e">/api/reports/absences</font>', st_cell),
        P('absentDays, absentDates[] (array de YYYY-MM-DD), bySucursal[]', st_cell),
        P('Art. 42 LFT (causas de suspensión); art. 47 (rescisión); art. 804 fr. III (controles de asistencia)', st_cell),
    ],
    [
        P('<b>Horas extra</b><br/><font size="6.5" color="#77756e">/api/reports/overtime</font>', st_cell),
        P('records[] (por registro): overtimeMinutes, overtimeDoubleMinutes, overtimeTripleMinutes, '
          'isRestDayWorked, restDayWorkedMinutes, restDayPremiumMinutes, isSunday; '
          'bySucursal[], byEmployee[], summary', st_cell),
        P('Art. 66 (HE dobles ≤9h/sem); art. 68 (HE triples >9h/sem); art. 73 (prima 100% descanso); '
          'art. 132 XXXIV (registro); NOM-035 (vigilar HE excesivas)', st_cell),
    ],
    [
        P('<b>Horas extra por empleado</b><br/><font size="6.5" color="#77756e">/api/reports/employee-overtime</font>', st_cell),
        P('byEmployee[] con dailyRecords[]: date, checkIn, checkOut, workedMinutes, '
          'overtimeMinutes, overtimeDoubleMinutes, overtimeTripleMinutes, isRestDayWorked, '
          'restDayWorkedMinutes, restDayPremiumMinutes, isSunday, status', st_cell),
        P('Art. 66, 68 (HE); art. 73 (prima descanso); art. 132 XXXIV (registro por día); '
          'NOM-035 (carga psicosocial por HE)', st_cell),
    ],
    [
        P('<b>Correcciones</b><br/><font size="6.5" color="#77756e">/api/reports/corrections</font>', st_cell),
        P('corrections[]: recordDate, originalCheckIn, originalCheckOut, currentCheckIn, currentCheckOut, '
          'workedMinutes, overtimeMinutes, status, correctionReason, correctedAt, correctedBy, '
          'justificationStatus; summary (bySucursal, byCorrector, affectedEmployees)', st_cell),
        P('Art. 132 XXXIV (trazabilidad de correcciones); art. 784 (carga de la prueba); '
          'NOM-037 art. 27 (inmutabilidad del registro)', st_cell),
    ],
    [
        P('<b>Diario</b><br/><font size="6.5" color="#77756e">/api/reports/daily</font>', st_cell),
        P('records[] (por registro): date, checkInTime, checkOutTime, status, workedMinutes, '
          'overtimeMinutes, overtimeDoubleMinutes, overtimeTripleMinutes, isRestDayWorked, '
          'restDayWorkedMinutes, restDayPremiumMinutes, isSunday, shiftType, nightMinutes, '
          'checkInLat/Long, checkInIp, checkInMethod; byEmployee[], summary', st_cell),
        P('Art. 132 XXXIV (registro electrónico); art. 60–61 (jornada nocturna); art. 66, 68 (HE); '
          'art. 73 (prima descanso); NOM-037 art. 27 (geolocalización, IP, método)', st_cell),
    ],
    [
        P('<b>Comparativo</b><br/><font size="6.5" color="#77756e">/api/reports/comparative</font>', st_cell),
        P('byEmployee[]: presentDays, absentDays, lateDays, earlyLeaveDays, totalOvertimeMinutes, '
          'totalDoubleMinutes, totalTripleMinutes, restDayWorkedCount, totalRestDayPremiumMinutes; '
          'summary (totales)', st_cell),
        P('Art. 132 XXXIV (registro); art. 66, 68 (HE); art. 73 (prima descanso); '
          'NOM-035 (vigilar patrones de ausencia/HE)', st_cell),
    ],
    [
        P('<b>STPS</b><br/><font size="6.5" color="#77756e">/api/reports/stps-format</font>', st_cell),
        P('3 secciones (Excel/PDF): Trabajadores (21 cols: nombre, puesto, sucursal, diasTrabajados, '
          'diasFaltaSinJustificar, <b>diasIncapacidad</b>, diasVacacionesDisfrutados, diasPermiso, '
          'diasDescansoTrabajados, diasLlegoTarde, totalRetardosMinutos, diasSalioTemprano, '
          'totalHorasExtraDobles, totalHorasExtraTriples, totalMinutosNocturnos, jornada, '
          'fueraGeofence, salarioBase); Movimientos; Resumen ejecutivo', st_cell),
        P('Art. 804 fr. III (controles de asistencia); art. 132 XXXIV (registro); art. 66, 68 (HE); '
          'art. 71, 72 (prima dominical, séptimo día); art. 73 (prima descanso); art. 76–80 (vacaciones); '
          'art. 60–61 (jornada nocturna); LSS art. 96, 170 (incapacidades); NOM-037 (geofence)', st_cell),
    ],
    [
        P('<b>Exportación multi-tipo</b><br/><font size="6.5" color="#77756e">/api/reports/export?type=</font>', st_cell),
        P('Genera CSV/XLSX según el parámetro <font face="Helvetica-Oblique">?type=</font>: '
          'Diario (<font face="Helvetica-Oblique">daily</font> — registros con lat/long/IP/método, '
          'auditRows de correcciones), Horas extra (<font face="Helvetica-Oblique">overtime</font> — HE dobles/triples, prima descanso), '
          'Incidencias (<font face="Helvetica-Oblique">incidences</font> — todas las métricas por empleado + totales), '
          'Comparativa (<font face="Helvetica-Oblique">comparative</font> — resumen comparativo), '
          'Ausencias (<font face="Helvetica-Oblique">absences</font> — fechas de ausencia)', st_cell),
        P('Art. 804 fr. III–IV (controles + comprobantes); art. 132 XXXIV (registro); art. 66, 68 (HE); '
          'art. 73 (prima descanso); NOM-037 art. 27 (lat/long/IP/método para prueba plena)', st_cell),
    ],
    [
        P('<b>Mi exportación (empleado)</b><br/><font size="6.5" color="#77756e">/api/reports/my-export</font>', st_cell),
        P('Por registro: Fecha, Entrada, Descanso Inicio/Fin, Salida, Estado, Hrs. Trabajadas, '
          'Hrs. Extra (dobles/triples como subtexto), Min. extra, Descanso (Sí/No), Prima 100% (min), '
          'Domingo (Sí/No), <b>Firmado</b> (employeeSignedAt), ¿Corregido?, Motivo corrección, Notas', st_cell),
        P('Art. 804 fr. III (control de asistencia); art. 132 XXXIV (registro); art. 66, 68 (HE); '
          'art. 73 (prima descanso); art. 71 (prima dominical); <b>NOM-037 art. 27 (firma = prueba plena)</b>', st_cell),
    ],
]

campos_tbl = Table(campos_rows, colWidths=COL_W2, repeatRows=1)
campos_style = TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('FONTNAME', (0, 0), (-1, 0), BASE_FONT_BOLD),
    ('FONTSIZE', (0, 0), (-1, 0), 8),
    ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
    ('VALIGN', (0, 0), (-1, 0), 'MIDDLE'),
    ('TOPPADDING', (0, 0), (-1, 0), 6),
    ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
    ('VALIGN', (0, 1), (-1, -1), 'TOP'),
    ('ALIGN', (0, 1), (-1, -1), 'LEFT'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 1), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
    ('FONTNAME', (0, 1), (-1, -1), BASE_FONT),
    ('FONTSIZE', (0, 1), (-1, -1), 8),
    ('GRID', (0, 0), (-1, -1), 0.4, BORDER),
    ('LINEBELOW', (0, 0), (-1, 0), 1.0, HEADER_FILL),
])
for i in range(1, len(campos_rows)):
    if i % 2 == 0:
        campos_style.add('BACKGROUND', (0, i), (-1, i), TABLE_STRIPE)
campos_tbl.setStyle(campos_style)
story.append(campos_tbl)

story.append(PageBreak())

# ─────────────────────────────────────────────────────────────────
# TABLA 3 — Referencia legal rápida
# ─────────────────────────────────────────────────────────────────
story.append(P('3. Referencia legal rápida — lo que dice la ley', st_h2))
story.append(P(
    'Articulado mexicano aplicable al control de asistencia y la obligación patronal que cada disposición impone.',
    st_body_small
))
story.append(Spacer(1, 4))

COL_W4 = [70, 220, 524]
scale4 = CONTENT_W / sum(COL_W4)
COL_W4 = [w * scale4 for w in COL_W4]

ref_header = [
    P('Ley / Norma', st_cell_header),
    P('Artículo', st_cell_header),
    P('Obligación patronal relevante para control de asistencia', st_cell_header),
]
LFT = '<b>LFT</b>'
NOM035 = '<b>NOM-035</b>'
NOM037 = '<b>NOM-037</b>'
LSS = '<b>LSS</b>'

ref_rows = [
    ref_header,
    [P(LFT, st_cell), P('Art. 132 fr. XXXIV', st_cell),
     P('Llevar registro electrónico de jornada (inicio y fin) por cada trabajador. Multa: 250–5,000 UMA ($29,327–$586,550 MXN).', st_cell)],
    [P(LFT, st_cell), P('Art. 60–61', st_cell),
     P('Jornadas: diurna 8h, nocturna 7h, mixta 7.5h. Nocturna paga prima 25%.', st_cell)],
    [P(LFT, st_cell), P('Art. 66', st_cell),
     P('Horas extra dobles (200%) — primeras 9h por semana.', st_cell)],
    [P(LFT, st_cell), P('Art. 68', st_cell),
     P('Horas extra triples (300%) — excedente de 9h por semana.', st_cell)],
    [P(LFT, st_cell), P('Art. 71', st_cell),
     P('Prima dominical ≥25% sobre salario ordinario por cada domingo trabajado.', st_cell)],
    [P(LFT, st_cell), P('Art. 72', st_cell),
     P('Séptimo día: descanso semanal con goce de sueldo (1 día por 6 trabajados).', st_cell)],
    [P(LFT, st_cell), P('Art. 73', st_cell),
     P('Trabajo en día de descanso = pago doble + prima 25% si es domingo.', st_cell)],
    [P(LFT, st_cell), P('Art. 74–75', st_cell),
     P('Días de descanso obligatorio. Trabajarlo paga doble (triple si es domingo).', st_cell)],
    [P(LFT, st_cell), P('Art. 76–80', st_cell),
     P('Vacaciones (mínimo 12 días en primer año); prima vacacional 25%.', st_cell)],
    [P(LFT, st_cell), P('Art. 784', st_cell),
     P('Carga de la prueba: en conflicto de jornada, el patrón debe demostrar sus dichos con registros.', st_cell)],
    [P(LFT, st_cell), P('Art. 804', st_cell),
     P('Conservar y exhibir: contratos, listas de raya, controles de asistencia, comprobantes de seguridad social. Conservación ≥1 año tras terminación.', st_cell)],
    [P(LFT, st_cell), P('Art. 805', st_cell),
     P('Incumplir art. 804 = presunción de ciertos los hechos del actor.', st_cell)],
    [P(NOM035, st_cell), P('STPS-2018', st_cell),
     P('Identificación de factores de riesgo psicosocial. Vigilar HE excesivas, ausencia de descanso semanal, días consecutivos largos.', st_cell)],
    [P(NOM037, st_cell), P('STPS-2023 art. 27', st_cell),
     P('Teletrabajo: los registros harán prueba plena si fueron acordados (firmados) con el trabajador. Geolocalización opcional.', st_cell)],
    [P(LSS, st_cell), P('Art. 15', st_cell),
     P('Obligación del patrón de registrar movimientos afiliatorios y conservar comprobantes de seguridad social por 5 años (SUA/IDSE).', st_cell)],
    [P(LSS, st_cell), P('Art. 41, 51', st_cell),
     P('Riesgos de trabajo: accidentes y enfermedades de trabajo. Reporte ST-7 al IMSS.', st_cell)],
    [P(LSS, st_cell), P('Art. 96', st_cell),
     P('Incapacidad por enfermedad general — 52 semanas pagadas a 60% del salario.', st_cell)],
    [P(LSS, st_cell), P('Art. 170', st_cell),
     P('Incapacidad por maternidad — 12 semanas pagadas a 100% del salario.', st_cell)],
]
ref_tbl = Table(ref_rows, colWidths=COL_W4, repeatRows=1)
ref_style = TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('FONTNAME', (0, 0), (-1, 0), BASE_FONT_BOLD),
    ('FONTSIZE', (0, 0), (-1, 0), 8.5),
    ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
    ('VALIGN', (0, 0), (-1, 0), 'MIDDLE'),
    ('TOPPADDING', (0, 0), (-1, 0), 6),
    ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
    ('VALIGN', (0, 1), (-1, -1), 'MIDDLE'),
    ('ALIGN', (0, 1), (-1, -1), 'LEFT'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 1), (-1, -1), 5),
    ('BOTTOMPADDING', (0, 1), (-1, -1), 5),
    ('FONTNAME', (0, 1), (-1, -1), BASE_FONT),
    ('FONTSIZE', (0, 1), (-1, -1), 8.5),
    ('GRID', (0, 0), (-1, -1), 0.4, BORDER),
    ('LINEBELOW', (0, 0), (-1, 0), 1.0, HEADER_FILL),
])
for i in range(1, len(ref_rows)):
    if i % 2 == 0:
        ref_style.add('BACKGROUND', (0, i), (-1, i), TABLE_STRIPE)
ref_tbl.setStyle(ref_style)
story.append(ref_tbl)

story.append(Spacer(1, 12))
story.append(P(
    '<b>Fuentes:</b> Ley Federal del Trabajo (texto vigente); '
    'NOM-035-STPS-2018; NOM-037-STPS-2023; Ley del Seguro Social; Justia (art. 803–804 LFT).',
    st_legend
))

# ━━ Build ━━
doc.build(story, onFirstPage=on_page, onLaterPages=on_page)

# Reportar
size_kb = os.path.getsize(OUT_PATH) / 1024
print(f'✓ PDF generado: {OUT_PATH}')
print(f'  Tamaño: {size_kb:.1f} KB')
